# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='soccerApp.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='soccerApp.Team'),
        ),
    ]
