# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerApp', '0005_auto_20170329_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='playedGames',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='totalPoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='totalVictories',
            field=models.IntegerField(default=0),
        ),
    ]
