# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerApp', '0006_auto_20170331_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='playedGames',
            field=models.IntegerField(default=0),
        ),
    ]
