# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerApp', '0007_auto_20170331_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='list1',
            field=models.CharField(default='ho', max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='list2',
            field=models.CharField(default='ho', max_length=200),
        ),
    ]
